# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ae/Purple-Lang

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ae/Purple-Lang

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ae/Purple-Lang/CMakeFiles /home/ae/Purple-Lang//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ae/Purple-Lang/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Purple

# Build rule for target.
Purple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Purple
.PHONY : Purple

# fast build rule for target.
Purple/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Purple.dir/build.make CMakeFiles/Purple.dir/build
.PHONY : Purple/fast

purple.o: purple.c.o
.PHONY : purple.o

# target to build an object file
purple.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Purple.dir/build.make CMakeFiles/Purple.dir/purple.c.o
.PHONY : purple.c.o

purple.i: purple.c.i
.PHONY : purple.i

# target to preprocess a source file
purple.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Purple.dir/build.make CMakeFiles/Purple.dir/purple.c.i
.PHONY : purple.c.i

purple.s: purple.c.s
.PHONY : purple.s

# target to generate assembly for a file
purple.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Purple.dir/build.make CMakeFiles/Purple.dir/purple.c.s
.PHONY : purple.c.s

tokenizer.o: tokenizer.c.o
.PHONY : tokenizer.o

# target to build an object file
tokenizer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Purple.dir/build.make CMakeFiles/Purple.dir/tokenizer.c.o
.PHONY : tokenizer.c.o

tokenizer.i: tokenizer.c.i
.PHONY : tokenizer.i

# target to preprocess a source file
tokenizer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Purple.dir/build.make CMakeFiles/Purple.dir/tokenizer.c.i
.PHONY : tokenizer.c.i

tokenizer.s: tokenizer.c.s
.PHONY : tokenizer.s

# target to generate assembly for a file
tokenizer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Purple.dir/build.make CMakeFiles/Purple.dir/tokenizer.c.s
.PHONY : tokenizer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Purple"
	@echo "... purple.o"
	@echo "... purple.i"
	@echo "... purple.s"
	@echo "... tokenizer.o"
	@echo "... tokenizer.i"
	@echo "... tokenizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

